name: Telegram Test Notification
on:
  schedule:
#    - cron: '0 3 * * *' # Runs every day at 8:30 AM
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve script for repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the notification script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python telegram_alert.py